### ISSUE TITLE
process_subclips() does not work

### ISSUE THREAD

**Issue by n400peanuts** [mexca/mexca#35]
It keeps selecting the whole video, rather than what it is indicated within process_subclips()

**Comment by n400peanuts** [comment]
I am running the latest version of mexca available from github. I am able to get this bug by reproducing the demo notebook, when running the `output = pipeline.apply(filename, process_subclip=(19, 29))` cell. 

`process_subclip` is completely ignored (i.e., the pipeline is applied to the whole video) and does not throw any error. Are you sure the video you are processing is not already trimmed?

**Comment by maltelueken** [comment]
This seems to be outdated, so I will close this for now.
